application: buzz-analysis
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js
 
- url: /plugin
  static_dir: plugin

- url: /lib
  static_dir: lib 
  
- url: /.*
  script: buzz.app